[package]
name = "carboxyl"
version = "0.1.0"
edition = "2024"

[features]
default = ["native-text"]
native-text = []

[dependencies]
rustls = "0.23"
servo = "0.3"
url = "2.5"
clap = { version = "4", features = ["derive"] }
ratatui = { version = "0.30", default-features = false, features = ["crossterm", "layout-cache"] }
rustix = { version = "1", features = ["termios", "stdio", "process"] }
dpi = "0.1"
unicode-width = "0.2"
log = "0.4"
simplelog = "0.12"
glam = "0.33"
signal-hook = "0.4"
anyhow = "1"

# release optimizations: must be used for builds
[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
