name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and Release
    runs-on: self-hosted # giant-rat (runs arch linux), provided by lysator

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: target/release/carboxyl
          generate_release_notes: true
