name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build, Test, Clippy
    runs-on: self-hosted # giant-rat (runs arch linux), provided by lysator :)

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install system dependencies
        run: |
          sudo pacman -Syu --noconfirm
          sudo pacman -S --noconfirm --needed \
            base-devel \
            pkgconf \
            openssl \
            mesa \
            fontconfig

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose

      - name: Run Tests
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy
