name: Rust

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Build, Test, Clippy
    runs-on: self-hosted # giant-rat (runs arch linux), provided by lysator :)

    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Tests
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy
